### ISSUE TITLE
Problem running bot with the new bot.js

### ISSUE THREAD

**Issue by master3395** [Gotowka/autorskieakcje#1]
I keep getting these errors when i try to turn my bot online using cmd.
Is it not compatible with DBM?
I'm using 2.1.6 atm.
Discordjs v13.8.0
I tried with v14.1.2 but same problem.

![image](https://user-images.githubusercontent.com/4199669/183269554-7ea0e657-aec3-4ea1-8358-458f612053b5.png)

**Comment by Gotowka** [comment]
Is that error using discord.js v14?
